# Generated by Django 2.2 on 2020-12-11 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('bg_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vps', models.IntegerField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_tracker_app.Play')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_tracker_app.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_players', to='board_game_tracker_app.User'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_name', to='board_game_tracker_app.User'),
        ),
        migrations.AddField(
            model_name='play',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='board_game_tracker_app.User'),
        ),
        migrations.AddField(
            model_name='play',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board_game_tracker_app.Board_Game'),
        ),
        migrations.AddField(
            model_name='play',
            name='players',
            field=models.ManyToManyField(related_name='plays', through='board_game_tracker_app.Score', to='board_game_tracker_app.Player'),
        ),
        migrations.AddField(
            model_name='play',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='num_of_wins', to='board_game_tracker_app.Player'),
        ),
        migrations.AddField(
            model_name='board_game',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorites', to='board_game_tracker_app.User'),
        ),
    ]
