# Generated by Django 2.2 on 2020-12-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='vps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
