# Generated by Django 2.2 on 2020-12-11 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_tracker_app', '0002_auto_20201210_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='board_game_tracker_app.Player'),
        ),
    ]
