# Generated by Django 2.2 on 2020-12-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_tracker_app', '0003_auto_20201210_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='board_game_tracker_app.Play'),
        ),
    ]
